[package]
name = "keychainstore-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Credentials",
    "Win32_Security_Cryptography"
]
