[package]
name = "keychainstore-macos"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = "1.0.6"
objc2 = "0.5.1"

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { version = "1.0.6", features = ["build"]}
