[package]
name = "geolocation-win"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.54.0"
features = ["Win32_Foundation", "Security_Credentials_UI", "Win32_System_WinRT"]
